### ISSUE TITLE
the message "is Supported = false"

### ISSUE THREAD

**Issue by HSIN-JU** [myflashlab/AR-ANE-Samples#3]
Hi Sir,

I can package this demo code and then setup success .apk file.
Regarding the message "is Supported = false", I got  "startAR=false".
 
Have any suggestions with  issues?

**Comment by myflashlab** [comment]
When isSupported is false, it can have different reasons but most probably it's because you have not replaced the dx.jar in your AdobeAir SDK with the latest version from Android SDK. please read https://github.com/myflashlab/AR-ANE-Samples/blob/master/ReadMe.pdf and make sure you are replacing the dx.jar correctly.

if you still have the problem, also make sure you are setting the manifest permissions and activities correctly in your project.

**Comment by HSIN-JU** [comment]
Hi Sir,

Many thanks.
I put actually metaio SDK Signatures to " <meta-data
android:name="MetaioLicenseString"
android:value="b115ORAEwkcAQAhfJPqBrQnKOmNBIc3Y59MsVbo7YVQ=" /> " that id
is "com.doitflash.ARPOI".

it show "  No Valid license Provided "
Have any suggestions?

Regards,
Cindy

2015-05-19 12:14 GMT+08:00 myflashlab <notifications@github.com>:

**Comment by myflashlab** [comment]
when building on Android, it will automatically adds "air." to the beginning of your app package name. when creating your package in Metaio, you should consider that.
