### ISSUE TITLE
Where can I find the Scrollers and what one is best for Apps

### ISSUE THREAD

**Issue by PapaDeBeau** [myflashlab/AR-ANE-Samples#8]
I am trying to find a scroller for my Andriod/ios app. What is the best one to use and how can I use it with any MovieClip?   I am trying to follow the example in the one on got with my new flash club membership but I can't seem to get it to work. I don't understand how to replace the embeded content with my content, that is any movieclip. Can you help me? 

Thanks

**Comment by PapaDeBeau** [comment]
I am now working on the starling abstract version of the scroller and I am sure I am linking it right but I get this Error: 1017: The definition of base class MyStarlingSprite was not found.

I am using the Flash CC IDE. What am I doing wrong?

**Comment by myflashlab** [comment]
MyStarlingSprite is actually extended from starling Sprite class. Find the
class in src.com.doitflash...... Folder in the sample project. You can use
a Sprite instead of course. Please use the sample codes first and get to
know how the scroller works inside the demo projects and then, you will be
able to implement it in your own project in no time :) all our scrollbars
have been on sale since 2009 and hundreds of users are using them. You'll
love them :) by the way, this is the Augmented Reality repository! Our
scrollers are not on github so you can just directly email us. Thanks.

On Monday, January 25, 2016, Ed <notifications@github.com> wrote:

> I am now working on the starling abstract version of the scroller and I am
> sure I am linking it right but I get this Error: 1017: The definition of
> base class MyStarlingSprite was not found.
>
> I am using the Flash CC IDE. What am I doing wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myflashlab/AR-ANE-Samples/issues/8#issuecomment-174545976>
> .
>


-- 
Sent from iPhone
